/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stairs.glb -t -T -p6 
Files: stairs.glb [4.74KB] > /Users/kawai/Desktop/floating-island/public/stairs-transformed.glb [3KB] (37%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.Mesh;
    Cube006: THREE.Mesh;
  };
  materials: object;
};

export function Torii(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/torii-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[1.047147, 5.083312, 8.322669]}
        rotation={[0, -0.675151, 0]}
        scale={[4.415971, 4.41597, 4.415971]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[4.22736, 13.164743, 11.364245]}
        rotation={[0, -0.46631, 0]}
        scale={0.614035}
      />
    </group>
  );
}

useGLTF.preload("/stairs-transformed.glb");
