/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sleepyFatCat.glb -t -T -p6 
Files: sleepyFatCat.glb [7.87MB] > /Users/kawai/Desktop/floating-island/public/sleepyFatCat-transformed.glb [1.67MB] (79%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useEffect, useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Icosphere: THREE.Mesh;
  };
  materials: Record<string, THREE.Material>;
  animations: THREE.AnimationClip[];
};

export function SleepyFatCat(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/sleepyFatCat-transformed.glb") as GLTFResult;
  const meshRef = useRef<THREE.Mesh>(null);
  const [morphTargetInfluences, setMorphTargetInfluences] = useState<number[]>([]);

  // Initialize morph target influences
  useEffect(() => {
    if (nodes.Icosphere.morphTargetInfluences) {
      setMorphTargetInfluences([...nodes.Icosphere.morphTargetInfluences]);
    }
  }, [nodes]);

  // Animation loop
  useFrame((state) => {
    if (meshRef.current && meshRef.current.morphTargetInfluences) {
      // Example: Animate the first morph target with a sine wave
      const time = state.clock.getElapsedTime();
      meshRef.current.morphTargetInfluences[0] = Math.sin(time) * 0.5 + 0.5;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        name="Icosphere"
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        morphTargetDictionary={nodes.Icosphere.morphTargetDictionary}
        morphTargetInfluences={morphTargetInfluences}
        position={[7.753144, 5.317592, -13.264419]}
        rotation={[-Math.PI, 0.77316, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/sleepyFatCat-transformed.glb");
