/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rock.glb -t -T -p6 
Files: rock.glb [477.49KB] > /Users/kawai/Desktop/floating-island/public/rock-transformed.glb [284.84KB] (40%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    rock001: THREE.Mesh;
  };
  materials: object;
};

export function Rock(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/rock-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rock001.geometry} material={nodes.rock001.material} position={[1.639191, 4.905804, -0.388305]} />
    </group>
  );
}

useGLTF.preload("/rock-transformed.glb");
